
print(P1.answer())
print(P2.answer())
print(P3.answer())
print(P4.answer())
print(P5.answer())
print(P6.answer())
print(P7.answer())
print(P8.answer())
print(P9.answer())
print(P10.answer())
print(P11.answer())
print(P12.answer())
