
print(P1.answer())
print(P2.answer())
print(P3.answer())
print(P4.answer())
print(P5.answer())
print(P6.answer())
print(P7.answer())
print(P8.answer())
print(P9.answer())
print(P10.answer())
print(P11.answer())
print(P12.answer())
print(P13.answer())
print(P14.answer())
print(P15.answer())
print(P16.answer())
print(P17.answer())
print(P18.answer())
print(P19.answer())
print(P20.answer())
print(P21.answer())
print(P22.answer(sorted: P22.answer()))
print(P23.answer())
print(P24.answer())
print(P25.answer())
print(P26.answer())
